alias k="kubectl"
alias d="docker"
alias ssh="ssh -v"
alias kl="kubectl logs --tail 100"
alias klf="kubectl logs --tail 100 -f"
alias vi="nvim"
# alias cd="zoxide"

# git
alias ga="git add"
alias gd="git diff"
alias gdc="git diff --cached"
alias gds="git diff --staged"
alias gco="git checkout"
alias gst="git status"
alias gc="git commit -v"
alias gca="git commit -v -a"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gcb="git checkout -b"
alias gcp="git cherry-pick"
alias gcl="git clone"
alias gp="git push"
alias glg="git log --stat"
alias glgg="git log --graph"
alias glgga="git log --graph --decorate --all"
alias glog="git log --oneline --decorate --color --graph"
alias gloga="git log --oneline --decorate --color --graph --all"
alias gsw="git switch"
alias gswc="git switch --create"

# claude
alias claude="$HOME/.claude/local/claude"
